name: Windows latest

on: [push]

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    #- name: Install dependencies
    #  run: |
    #    sudo apt update
    #    sudo apt install -y libusb-dev
    #- name: configure
    #  run: ./configure
    - name: make
      run: make mingw
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
