name: OSX latest

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew update
        brew install libusb-compat
        brew install hidapi
    #- name: configure
    #  run: ./configure
    - name: make 
      run: make TARGETOS=osx
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
